### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hkirk/java-html2image#20]
```
Hi,

I can see that there are no commit since 2010, no closed defect.
Is this project dead ? Is there any alternative/fork ? vI can't find it on the 
internet

thanks
```

Original issue reported on code.google.com by `jp.caru...@gmail.com` on 12 Jun 2014 at 1:01

**Comment by hkirk** [comment]
I've copied the project to github - mostly because I needed the project and wanted to keep the code alive. But hopefully I'll have some time to fix some of the issues

PR are welcome.
