### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by kregoslup** [hkirk/java-html2image#25]
Hi,

Do you happen to know what is the license of this project? Is it http://www.gnu.org/licenses/lgpl.html as in https://code.google.com/archive/p/java-html2image/ ?

**Comment by hkirk** [comment]
Yes, I can see the problem, so the project was originally forked from code.google.com/p/java-html2image, where the license wa: GNU Lesser GPL, so I'll update the README with the same license.
