### ISSUE TITLE
jpg files have an orange background

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hkirk/java-html2image#5]
```
What steps will reproduce the problem?
1. convert html to jpg
2.
3.

What is the expected output? 
html without a background color will generate jpg files without a background 
color
 
What do you see instead?
html without a background color will generate nice gif and png output, but jpg 
output files have always an orange background

What version of the product are you using? 
version 0.9

On what operating system?
windows 7 - 64 bit


Please provide any additional information below.


```

Original issue reported on code.google.com by `heiko.pi...@gmail.com` on 25 Oct 2011 at 5:49

Attachments:
* [cmt_1.html.jpg](https://storage.googleapis.com/google-code-attachments/java-html2image/issue-5/comment-0/cmt_1.html.jpg)
* [cmt_1.html.png](https://storage.googleapis.com/google-code-attachments/java-html2image/issue-5/comment-0/cmt_1.html.png)
* [cmt_1.html](https://storage.googleapis.com/google-code-attachments/java-html2image/issue-5/comment-0/cmt_1.html)

**Comment by hkirk** [comment]
Merged into branch and tested
